#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Merge script: Combines all batch entity files into the final fine_grained_entities_data.py
"""
import sys, os, importlib

sys.stdout.reconfigure(encoding='utf-8')
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__))))

from fine_grained_entities_data import CORE_WIKILINK_KEYWORDS as orig_kw
from fine_grained_entities_data import MASTER_DEDICATED_ENTITIES as orig
from batch_a_itto_docs import BATCH_ENTITIES as batch_a
from batch_b_tools import BATCH_ENTITIES as batch_b
from batch_c_ch1to9 import BATCH_ENTITIES as batch_c
from batch_d_ch15to17 import BATCH_ENTITIES as batch_d

all_entities = orig + batch_a + batch_b + batch_c + batch_d

# Collect all aliases from all entities to expand the wikilink keywords
all_aliases = set(orig_kw)
for e in all_entities:
    for a in e.get('aliases', []):
        all_aliases.add(a)
    # Also add the filename stem
    stem = e['filename'].replace('.md', '')
    all_aliases.add(stem)

# Sort keywords for deterministic output
sorted_kw = sorted(all_aliases, key=lambda x: (-len(x), x))

# Write the merged file
output_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'fine_grained_entities_data.py')

with open(output_path, 'w', encoding='utf-8') as f:
    f.write('#!/usr/bin/env python3\n')
    f.write('# -*- coding: utf-8 -*-\n')
    f.write('"""\n')
    f.write('Master Fine-Grained Knowledge Entities Database (MERGED)\n')
    f.write(f'Total entities: {len(all_entities)}\n')
    f.write('Generated by merge_entities.py\n')
    f.write('"""\n\n')
    
    # Write CORE_WIKILINK_KEYWORDS
    f.write('CORE_WIKILINK_KEYWORDS = [\n')
    for i, kw in enumerate(sorted_kw):
        comma = ',' if i < len(sorted_kw) - 1 else ''
        f.write(f'    "{kw}"{comma}\n')
    f.write(']\n\n')
    
    # Write MASTER_DEDICATED_ENTITIES
    f.write('MASTER_DEDICATED_ENTITIES = [\n')
    for ent in all_entities:
        f.write('    {\n')
        f.write(f'        "ch_num": {ent["ch_num"]},\n')
        f.write(f'        "filename": """{ent["filename"]}""",\n')
        f.write(f'        "title": """{ent["title"]}""",\n')
        f.write(f'        "category": """{ent["category"]}""",\n')
        f.write(f'        "section": """{ent["section"]}""",\n')
        
        import json
        f.write(f'        "tags": {json.dumps(ent["tags"], ensure_ascii=False)},\n')
        f.write(f'        "aliases": {json.dumps(ent["aliases"], ensure_ascii=False)},\n')
        
        # Escape the content for triple-quoted string
        content = ent["content"]
        f.write(f'        "content": """{content}"""\n')
        f.write('    },\n')
    f.write(']\n')

print(f'Merged {len(all_entities)} entities into {output_path}')
print(f'Keywords expanded to {len(sorted_kw)} entries')
